# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Tue Sep 11 12:17:49 2012
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(442, 401)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/imagenes/icono")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 141, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.sldInterval = QtGui.QSlider(self.centralwidget)
        self.sldInterval.setGeometry(QtCore.QRect(10, 70, 231, 19))
        self.sldInterval.setMinimum(1)
        self.sldInterval.setMaximum(1440)
        self.sldInterval.setProperty("value", 30)
        self.sldInterval.setOrientation(QtCore.Qt.Horizontal)
        self.sldInterval.setObjectName(_fromUtf8("sldInterval"))
        self.btnStart = QtGui.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(10, 100, 231, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/imagenes/imagenes/Glasses.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnStart.setIcon(icon1)
        self.btnStart.setObjectName(_fromUtf8("btnStart"))
        self.lcdFollowers = QtGui.QLCDNumber(self.centralwidget)
        self.lcdFollowers.setGeometry(QtCore.QRect(320, 10, 111, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdFollowers.setFont(font)
        self.lcdFollowers.setToolTip(_fromUtf8(""))
        self.lcdFollowers.setAutoFillBackground(False)
        self.lcdFollowers.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    color: rgb(0, 0, 0 );    \n"
"    background-color: rgb(55,55,55);\n"
"}"))
        self.lcdFollowers.setNumDigits(10)
        self.lcdFollowers.setObjectName(_fromUtf8("lcdFollowers"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 20, 61, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.btnViewLog = QtGui.QPushButton(self.centralwidget)
        self.btnViewLog.setGeometry(QtCore.QRect(10, 140, 231, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/imagenes/imagenes/log.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnViewLog.setIcon(icon2)
        self.btnViewLog.setObjectName(_fromUtf8("btnViewLog"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 40, 181, 171))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/imagenes/logo")))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.btnSaveChart = QtGui.QPushButton(self.centralwidget)
        self.btnSaveChart.setGeometry(QtCore.QRect(10, 180, 231, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/imagenes/imagenes/chart.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSaveChart.setIcon(icon3)
        self.btnSaveChart.setIconSize(QtCore.QSize(20, 20))
        self.btnSaveChart.setObjectName(_fromUtf8("btnSaveChart"))
        self.lcdInterval = QtGui.QLCDNumber(self.centralwidget)
        self.lcdInterval.setGeometry(QtCore.QRect(150, 40, 91, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdInterval.setFont(font)
        self.lcdInterval.setToolTip(_fromUtf8(""))
        self.lcdInterval.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    color: rgb(0, 0, 0 );    \n"
"    background-color: rgb(55,55,55);\n"
"}\n"
""))
        self.lcdInterval.setNumDigits(10)
        self.lcdInterval.setProperty("intValue", 30)
        self.lcdInterval.setObjectName(_fromUtf8("lcdInterval"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 220, 421, 101))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 40, 131, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 131, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.spbTimeout = QtGui.QSpinBox(self.frame)
        self.spbTimeout.setGeometry(QtCore.QRect(140, 30, 91, 22))
        self.spbTimeout.setToolTip(_fromUtf8(""))
        self.spbTimeout.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.spbTimeout.setReadOnly(False)
        self.spbTimeout.setMinimum(30)
        self.spbTimeout.setMaximum(3600)
        self.spbTimeout.setObjectName(_fromUtf8("spbTimeout"))
        self.spbRetries = QtGui.QSpinBox(self.frame)
        self.spbRetries.setGeometry(QtCore.QRect(140, 60, 91, 22))
        self.spbRetries.setToolTip(_fromUtf8(""))
        self.spbRetries.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.spbRetries.setReadOnly(False)
        self.spbRetries.setMinimum(1)
        self.spbRetries.setMaximum(999999999)
        self.spbRetries.setProperty("value", 5)
        self.spbRetries.setObjectName(_fromUtf8("spbRetries"))
        self.spbMinDelay = QtGui.QSpinBox(self.frame)
        self.spbMinDelay.setGeometry(QtCore.QRect(320, 30, 91, 22))
        self.spbMinDelay.setToolTip(_fromUtf8(""))
        self.spbMinDelay.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.spbMinDelay.setReadOnly(False)
        self.spbMinDelay.setMinimum(1)
        self.spbMinDelay.setMaximum(999999999)
        self.spbMinDelay.setProperty("value", 1)
        self.spbMinDelay.setObjectName(_fromUtf8("spbMinDelay"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(240, 70, 71, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(240, 40, 71, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.spbMaxDelay = QtGui.QSpinBox(self.frame)
        self.spbMaxDelay.setGeometry(QtCore.QRect(320, 60, 91, 22))
        self.spbMaxDelay.setToolTip(_fromUtf8(""))
        self.spbMaxDelay.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.spbMaxDelay.setReadOnly(False)
        self.spbMaxDelay.setMinimum(1)
        self.spbMaxDelay.setMaximum(999999999)
        self.spbMaxDelay.setProperty("value", 4)
        self.spbMaxDelay.setObjectName(_fromUtf8("spbMaxDelay"))
        self.btnAbout = QtGui.QPushButton(self.centralwidget)
        self.btnAbout.setGeometry(QtCore.QRect(10, 330, 421, 61))
        self.btnAbout.setIcon(icon)
        self.btnAbout.setIconSize(QtCore.QSize(48, 48))
        self.btnAbout.setObjectName(_fromUtf8("btnAbout"))
        self.cboAccount = QtGui.QComboBox(self.centralwidget)
        self.cboAccount.setGeometry(QtCore.QRect(110, 10, 131, 26))
        self.cboAccount.setToolTip(_fromUtf8(""))
        self.cboAccount.setObjectName(_fromUtf8("cboAccount"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Twitter Followers Keeper", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Account name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Check interval (mins):", None, QtGui.QApplication.UnicodeUTF8))
        self.btnStart.setText(QtGui.QApplication.translate("MainWindow", "Start Keeping!", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Followers:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnViewLog.setText(QtGui.QApplication.translate("MainWindow", "View Log", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSaveChart.setText(QtGui.QApplication.translate("MainWindow", "Save chart", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Advanced settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Connection Timeout:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Connection Retries:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Max. Delay:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Min. Delay:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAbout.setText(QtGui.QApplication.translate("MainWindow", "About TFK ...", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
